### ISSUE TITLE
没看懂安装步骤，好复杂~

### ISSUE THREAD

**Issue by 1825921819** [fesiong/goblog#16]
没看懂部署、安装步骤，好复杂~/捂脸.jpg

**Comment by fesiong** [comment]
你可以从右侧的release中下载我编译好的软件包，不需要配置复杂的环境就可以使用。如果你想自己编译而不会编译的话，可以从https://www.kandaoni.com 上的教程找到方法。golang安装教程https://www.kandaoni.com/article/3
