### ISSUE TITLE
怎麼建立一個帳號密碼

### ISSUE THREAD

**Issue by tonyhsu0111** [fesiong/goblog#17]
怎麼建立一個帳號密碼，建立有產生資料庫，但沒有辦法設定一組帳號密碼

**Comment by fesiong** [comment]
删除根目录下的config.json，然后重新运行程序，在浏览器访问 https://localhost:8001/  ，它会出现一个安装界面，要求你填写数据库信息和管理员账号密码。

**Comment by tonyhsu0111** [comment]
> 删除根目录下的config.json，然后重新运行程序，在浏览器访问 https://localhost:8001/ ，它会出现一个安装界面，要求你填写数据库信息和管理员账号密码。

有刪除過了，不過不會帶入安裝介面
會出現500
系统给程序员提了一个bug，程序员正在修复中：(Unexpected) internal server error

**Comment by fesiong** [comment]
Terminal的输出信息贴出来看下

**Comment by tonyhsu0111** [comment]
> Terminal的输出信息贴出来看下


[WARN] 2021/01/26 11:22 Recovered from a route's Handler('irisweb/controller.Common')
At Request: 200 /favicon.ico GET ::1
Trace: runtime error: invalid memory address or nil pointer dereference

/usr/local/go/src/runtime/panic.go:967
/usr/local/go/src/runtime/panic.go:212
/usr/local/go/src/runtime/signal_unix.go:687
/Users/Tony/go_workspace/pkg/mod/gorm.io/gorm@v1.20.7/gorm.go:285
/Users/Tony/go_workspace/pkg/mod/gorm.io/gorm@v1.20.7/chainable_api.go:145
/Users/Tony/Documents/DATA/wwwhome/go_code/goblog/provider/nav.go:12
/Users/Tony/Documents/DATA/wwwhome/go_code/goblog/controller/common.go:54
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
/Users/Tony/Documents/DATA/wwwhome/go_code/goblog/middleware/auth.go:18
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
/Users/Tony/Documents/DATA/wwwhome/go_code/goblog/middleware/options.go:13
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/middleware/recover/recover.go:55
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1030
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1217
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/handler.go:250
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:135
/Users/Tony/go_workspace/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:227
/usr/local/go/src/net/http/server.go:2807
/usr/local/go/src/net/http/server.go:1895
/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by fesiong** [comment]
谢谢反馈，正在修复
