### ISSUE TITLE
我用預設的帳號與密碼無法登入

### ISSUE THREAD

**Issue by tonyhsu0111** [fesiong/goblog#18]
目前有建立預設的帳號與密碼，但是無法登入
帳號:admin
密碼：123456

資料庫內的的密碼 :
$2a$04$oHBNr3IxvjMaJ9kX45QhZuIfMZuEnodZOIdyj35WCCh/L8QFX7zzW

**Comment by fesiong** [comment]
经测试，你资料库内对应的密码明文是：12345678

**Comment by tonyhsu0111** [comment]
code這段預設是
 func (bootstrap *Bootstrap) Serve() {
	//自动迁移表
	if config.DB != nil {
		_ = model.AutoMigrateDB(config.DB)
		//创建管理员，会先判断有没有的。不用担心重复
		_ = provider.InitAdmin("admin", "123456")
	}

**Comment by fesiong** [comment]
你用12345678试一下看看，因为我拿 $2a$04$oHBNr3IxvjMaJ9kX45QhZuIfMZuEnodZOIdyj35WCCh/L8QFX7zzW 和 12345678 比对是正确的。这个值应该是你在安装的时候输入的。上面预设部分只有在不是通过install初始化的时候，才会执行。

**Comment by tonyhsu0111** [comment]
> 你用12345678试一下看看，因为我拿 $2a$04$oHBNr3IxvjMaJ9kX45QhZuIfMZuEnodZOIdyj35WCCh/L8QFX7zzW 和 12345678 比对是正确的。这个值应该是你在安装的时候输入的。上面预设部分只有在不是通过install初始化的时候，才会执行。

是頁面的預設密碼問題
<div class="layui-form-item">
                        <label class="layui-form-label">后台密码</label>
                        <div class="layui-input-inline">
                            <input type="password" name="admin_password" value="12345678" required  lay-verify="required" placeholder="登录密码" autocomplete="off" class="layui-input">
                        </div>

**Comment by fesiong** [comment]
现在能正常使用了吗？

**Comment by tonyhsu0111** [comment]
> 现在能正常使用了吗？
YES，功能正常
