### ISSUE TITLE
请问在展示文章列表的时候可以取内容里的图片吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [fesiong/goblog#21]
![20210409083702](https://user-images.githubusercontent.com/12076232/114112438-fd1c1500-990e-11eb-952e-1550f3995709.png)

就像这种效果 在博客首页文章列表展示的时候  如果内容有图片就显示在列表上  如果没有就不显示  请问 要怎么取到内容里的图片？

**Comment by fesiong** [comment]
调用方法写在模板里了。参看index.html 或 category/article.html

`                  {% for item in articles %}
                        <li class="item">
                            <a href="{{getUrl("article", item, 0)}}" class="link flex-item">
                                <h5 class="title">{{item.Title}}</h5>
                                <div class="description">{{item.Description}}</div>
                                <div class="meta">
                                    {% if item.Category %}<span>{{item.Category.Title}}</span>{% endif %}
                                    <span>{{stampToDate(item.CreatedTime, "2006-01-02")}}</span>
                                    <span>{{item.Views}} 阅读</span>
                                </div>
                            </a>
                            {% if item.GetThumb() %}
                            <a href="{{getUrl("article", item, 0)}}" class="thumb">
                                <img class="thumb-image" alt="{{item.Title}}" src="{{item.GetThumb()}}">
                            </a>
                            {% endif %}
                        </li>
                        {% empty %}
                        <li class="item empty">
                            该列表没有任何内容
                        </li>
                        {% endfor %}`

**Comment by Yakumo-Yukari** [comment]
> 调用方法写在模板里了。参看index.html 或 category/article.html
> 
> ```
>                     {% for item in articles %}
>                         <li class="item">
>                             <a href="{{getUrl("article", item, 0)}}" class="link flex-item">
>                                 <h5 class="title">{{item.Title}}</h5>
>                                 <div class="description">{{item.Description}}</div>
>                                 <div class="meta">
>                                     {% if item.Category %}<span>{{item.Category.Title}}</span>{% endif %}
>                                     <span>{{stampToDate(item.CreatedTime, "2006-01-02")}}</span>
>                                     <span>{{item.Views}} 阅读</span>
>                                 </div>
>                             </a>
>                             {% if item.GetThumb() %}
>                             <a href="{{getUrl("article", item, 0)}}" class="thumb">
>                                 <img class="thumb-image" alt="{{item.Title}}" src="{{item.GetThumb()}}">
>                             </a>
>                             {% endif %}
>                         </li>
>                         {% empty %}
>                         <li class="item empty">
>                             该列表没有任何内容
>                         </li>
>                         {% endfor %}```
> ```

好的 谢谢了
