### ISSUE TITLE
大佬 可以加入博客加密功能吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [fesiong/goblog#22]
![1](https://user-images.githubusercontent.com/12076232/114113679-d1e6f500-9911-11eb-9fc7-8be5dd4a605a.png)

![image](https://user-images.githubusercontent.com/12076232/114113495-52592600-9911-11eb-996f-2c854ca0d206.png)

在发布博客的时候可以设置密码 其他人需要查看则需要输入正确的密码才能阅读

有时候自己的有些博客比较隐私所有就不方便所有人阅读 只有输入正确密码的人才能阅读

**Comment by fesiong** [comment]
这个可以考虑下
