### ISSUE TITLE
根据分类添加文章,点击首页导航分类显示404

### ISSUE THREAD

**Issue by aiminchen** [fesiong/goblog#23]
这个问题在最后一次提交之前也是存在的,
找了一下bug,主要是因为那个rewrite的动态路由造成的
因为后台在添加导航时,挂在分类下,那个link为空白,前端自动添加了link,格式为:类似(http://localhost:8001/c/1)这样的路由
然后这个路由被rewrite获取到,被当成了伪静态的路由进行处理,但是伪静态的地址是加了.html的后缀,
但是出现了服务重启也能打开,再次重启又404的奇怪现象.
我看那个blog版本下添加导航挂载分类下直接分配了link的,格式是category/id,在路由中也有category/{id}的路由,
还有一处bug,controller/category.go 文件中func CategoryArticlePage(ctx iris.Context) {}方法中categoryId 一直为0
,`if categoryVal == nil {
		categoryId = 0
	} else {
		category, _ = categoryVal.(*model.Category)
               //应该在此处添加一下下面的代码
		categoryId = category.Id
	}`

**Comment by fesiong** [comment]
谢谢支出，很快将会得到修复

**Comment by aiminchen** [comment]
重新检查了一遍,应该是正则那边的问题
![image](https://user-images.githubusercontent.com/15519238/114151037-4a1fdb80-994f-11eb-9b6e-a7933e4c4e11.png)
在for循环这个map的时候,key应该是随机的,先把")"换成了 ")?",然后发现了有?,又把?转成了\\?,最后就404了,
我把"?": "\\?",这个暂时去掉了,但是这个应该是需要的吧,虽然我也不知道这个?什么时候需要

**Comment by aiminchen** [comment]
重新检查了一遍,应该是正则那边的问题
![image](https://user-images.githubusercontent.com/15519238/114151037-4a1fdb80-994f-11eb-9b6e-a7933e4c4e11.png)
在for循环这个map的时候,key应该是随机的,先把")"换成了 ")?",然后发现了有?,又把?转成了\\?,最后就404了,
我把"?": "\\?",这个暂时去掉了,但是这个应该是需要的吧,虽然我也不知道这个?什么时候需要

**Comment by fesiong** [comment]
问题已得到修复。

**Comment by aiminchen** [comment]
nice点个赞
