### ISSUE TITLE
当伪静态规则改成命名模式后,首页导航就打不开了

### ISSUE THREAD

**Issue by aiminchen** [fesiong/goblog#24]
当伪静态规则改成命名模式后,服务器重启,文章详情连接变成了命名字符串,并且可以正常打开,但是导航就出现问题了,url全部变成了http://localhost:8001/c  
测试了一下http://localhost:8001/c/1  发现服务器是根据urlToken来查找分类的,但是数据库看了下,url_token数据是空的,是否是在切换命名模式的时候,没有更新category的url_token字段数据呢

**Comment by fesiong** [comment]
这个问题已经修复，原因是原先不会自动生成urlToken。现在已经增加自动生成URLToken了，因此你只需要重新编辑一下分类，就可以了

**Comment by fesiong** [comment]
由于已经存在的分类没有URLToken，程序没有写计划任务脚本，因此需要手动再次编辑保存下分类，让它生成URLToken。

**Comment by aiminchen** [comment]
测试了一下,现在是ok了,提一个修改意见,就是router的静态文件那一块,
因为本地开发,nginx不太方便,所以最后试了一下修改为下面的,静态文件访问就正常了,不知道这个项目中有没有其他哪里和这个有冲突
app.HandleDir("/static", fmt.Sprintf("%spublic/static", config.ExecPath))

**Comment by fesiong** [comment]
单纯这么改也不是办法，因我上传的图片在uploads文件夹，还是无法显示。本地配置nginx最好了

**Comment by aiminchen** [comment]
一个不行就两个,我再加一个HandleDir,哈哈
