### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by suifengqjn** [fesiong/goblog#27]
网站相当不错，唯独编辑器欠缺一点，现在很多网站都用这个，https://pandao.github.io/editor.md/，
接入也很方便，如果能支持markdown，博客迁移就很方便了

**Comment by fesiong** [comment]
谢谢， Thank you.

fengshi ***@***.***> 于 2021年12月28日周二 14:58写道：

**Comment by fesiong** [comment]
已发布全新的后台，使用wangeditor。
