### ISSUE TITLE
大佬建议加个自定义tags功能 有助于seo和内容搜索和识别

### ISSUE THREAD

**Issue by Yakumo-Yukari** [fesiong/goblog#28]
![1](https://user-images.githubusercontent.com/12076232/153735245-324b6c41-884e-44dc-b6a6-b073ae3780ff.PNG)

类似这种 红色部分tags是文章的分类 灰色tags是发布文章时候自定义添加的tags

**Comment by fesiong** [comment]
有开发计划的，只是还没来得及实现到

**Comment by fesiong** [comment]
你想要的功能已实现，欢迎使用 #25

**Comment by Yakumo-Yukari** [comment]
> 你想要的功能已实现，欢迎使用 在最新的分支

谢谢大佬
