### ISSUE TITLE
高老师，加油！

### ISSUE THREAD

**Issue by 1825921819** [fesiong/goblog#30]
要是有会员系统更好了，可以认证会员资质、充值、购买商品、优惠卷、关注粉丝，积分、获赞、评论、收藏等会员功能，辛苦了。

**Comment by fesiong** [comment]
会员系统在计划开发中，不久的将来就可以使用了

**Comment by wbwm** [comment]
> 会员系统在计划开发中，不久的将来就可以使用了

高老师，会员系统开发的怎么样了，最近一个月没更新了😄

**Comment by fesiong** [comment]
会员系统已增加。
