### ISSUE TITLE
你好，请教怎么在列表调用内容？

### ISSUE THREAD

**Issue by zhoushiya** [fesiong/goblog#31]
目前提供的item的for字段里没有content字段，只是{{item.Description}}，我想直接调用{{item.Content}}，应该怎么写？

后台模型管理里关了产品模型，但是添加栏目那里还会显示

**Comment by fesiong** [comment]
content 字段在列表中是没有加载的，如果你确实需要，你可以“文档详情标签”这样调用：
`{% archiveDetail with id=item.Id name="Content" %}`

添加栏目那里可能没有根据后台模型做判断，谢谢指出

**Comment by zhoushiya** [comment]
> 

非常感谢，已经成功调用，非常好的程序，期待会员模块

**Comment by zhoushiya** [comment]
请教怎么判断文章所含图片数量？我想判断组图大于2张才调用图片列表，却不生效，
```
{% if item.Images > 2 %}
<ul class="grid grid-cols-3 gap-3 pb-3">
{% for inner in item.Images %}
<li>
<a href="{{inner}}" class="block bg-cover bg-center w-20 sm:w-36 h-20 sm:h-36" style="background-image: url({{inner}})"> </a>
</li>
{% endfor %}
</ul>
{% endif %}
```

还得麻烦官方模版帮助加上搜索。。。

**Comment by fesiong** [comment]
> @fesiong 请教怎么判断文章所含图片数量？我想判断组图大于2张才调用图片列表，却不生效，
> 
> ```
> {% if item.Images > 2 %}
> <ul class="grid grid-cols-3 gap-3 pb-3">
> {% for inner in item.Images %}
> <li>
> <a href="{{inner}}" class="block bg-cover bg-center w-20 sm:w-36 h-20 sm:h-36" style="background-image: url({{inner}})"> </a>
> </li>
> {% endfor %}
> </ul>
> {% endif %}
> ```
> 
> 还得麻烦官方模版帮助加上搜索。。。

判断数量需要使用到 length 的filter，用if来做判断。如：
{% if item.Images|length > 2 %}这里是判断成功的代码{% endif %}

全文搜索的问题，我考虑下

**Comment by zhoushiya** [comment]
多谢，做个模板试试
