### ISSUE TITLE
go-imagequant apple 错误 error: "This header is only meant to be used on x86 and x64 architecture"

### ISSUE THREAD

**Issue by firma** [fesiong/goblog#37]
# github.com/ultimate-guitar/go-imagequant 这个库没人维护了，源代码包含内联汇编，这似乎与您使用的编译器想要的方言不同。使用内联汇编使得该程序不太可能在与编写它时不同的 CPU（系列）上未经修改地工作，从编译选项看来，它是 Intel x86-64

**Comment by fesiong** [comment]
这个问题我得研究下，如果换成pngquant的静态文件的话，也不太合适

**Comment by firma** [comment]
可以考虑 imagemagick

**Comment by firma** [comment]
RP https://github.com/fesiong/goblog/pull/38
