### ISSUE TITLE
MAC M1 编译不过

### ISSUE THREAD

**Issue by haitor888** [fesiong/goblog#42]
% go build -o anqicms main/main.go         
# command-line-arguments
/opt/homebrew/Cellar/go/1.21.3/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: unknown file type in '/private/var/folders/79/_92pblyn2hqg13wk1_n02xpw0000gn/T/go-link-1685129928/000000.o'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fesiong** [comment]
因为有anqicms.syso 在根目录，这是一个WIndows的图标文件，删掉后可以编译。
