### ISSUE TITLE
写错了

### ISSUE THREAD

**Issue by UnclePeel** [fesiong/goblog#47]
运行时报错，包正常引入
# github.com/chai2010/webp
..\vendor\github.com\chai2010\webp\webp.go:22:9: undefined: webpGetInfo
..\vendor\github.com\chai2010\webp\webp.go:26:20: undefined: webpDecodeGray
..\vendor\github.com\chai2010\webp\webp.go:39:20: undefined: webpDecodeRGB
..\vendor\github.com\chai2010\webp\webp.go:52:20: undefined: webpDecodeRGBA
..\vendor\github.com\chai2010\webp\webp.go:68:14: undefined: webpDecodeGrayToSize
..\vendor\github.com\chai2010\webp\webp.go:82:14: undefined: webpDecodeRGBToSize
..\vendor\github.com\chai2010\webp\webp.go:96:14: undefined: webpDecodeRGBAToSize
..\vendor\github.com\chai2010\webp\webp.go:109:7: undefined: toGrayImage
..\vendor\github.com\chai2010\webp\webp.go:110:14: undefined: webpEncodeGray
..\vendor\github.com\chai2010\webp\webp.go:119:14: undefined: webpEncodeRGB
..\vendor\github.com\chai2010\webp\webp.go:119:14: too many errors (exit status 1)

**Comment by fesiong** [comment]
不能跨系统编译

**Comment by fesiong** [comment]
你的这个错误是因为没有安装 gcc 。因为项目引入了webp，需要CGO_ENABLE, WIndows下需要安装 MinGW-w64，它是 
 C/C++编译器GCC的Windows版本
