### ISSUE TITLE
用户获取id逻辑有问题

### ISSUE THREAD

**Issue by UnclePeel** [fesiong/goblog#59]
标签用法：{% userDetail with name="Id" %}，自动获取当前用户的id，但是获取不到，userDetail 的id参数又是必须的，这是什么逻辑？

**Comment by fesiong** [comment]
你是在哪个地方使用的呢？可以说明下使用场景吗

**Comment by UnclePeel** [comment]
谢谢，我已经解决了，现在有一个重要问题请测试一下，用户权限控制，当一篇文章或者部分内容设置需要用户等级控制的时候，比如在文章里指定L1以上用户能看，登录后，前端整个页面就没有返回显示，空白~，
