### ISSUE TITLE
centos 编译的时候报错

### ISSUE THREAD

**Issue by kylo1005** [fesiong/goblog#61]
go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-4275926408/000000.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
![image](https://github.com/user-attachments/assets/337cb551-6ede-44fa-8b21-347ed5ce9dc3)
这个怎么解决？

**Comment by fesiong** [comment]
删除根目录下的 anqicms.syso 就可以编译了。anqicms.syso 是Windows的图标
